version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  node-api:
    container_name: api-login
    build: ./server/api
    depends_on:
      - security
    networks:
       - app-tier
    ports:
      - "3000:3000"
        
  node-api-blocked:
    container_name: api-blocked
    build: ./server/error
    networks:
      - app-tier
    ports:
      - "8000:8000"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - app-tier
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
     - app-tier
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
