###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################
services:
#################-node-Api-############################
   node-api:
    container_name: api-login
    restart: always
    build:
      context: ./server/api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    #volumes:
    #  - ./server/api:/app

###################-CLIENTE-###########################
   cliente:
    container_name: cliente
    build: ./client
    ports:
        - "4000:4000"
    depends_on:
        - node-api
        - node-api-blocked

#################-zookeeper-############################
   zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


#################-node-Api-blocked-############################
   node-api-blocked:
    container_name: api-blocked
    restart: always
    build:
      context: ./server/error/
      dockerfile: Dockerfile
    ports:
       - "8000:8000"
    #volumes:
    #   - ./server/error:/app/

#################-kafka-############################
   kafka:
    container_name: elkafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper