version: "3.1"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider

  kafka:
    image: confluentinc/cp-server:5.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
# version: "3.7"
# services:
#   zookeeper:
#     image: "bitnami/zookeeper:latest"
#     restart: always
#     environment:
#       ALLOW_ANONYMOUS_LOGIN: "yes"
#     ports:
#       - 2181:2181
#       - 2888:2888
#       - 3888:3888
#   kafka:
#     image: "bitnami/kafka:2.8.1"
#     restart: always
#     depends_on:
#       - zookeeper
#     environment:
#       ALLOW_PLAINTEXT_LISTENER: "yes"
#       KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
#     ports:
#       - 9092:9092
#   backend:
#     build:
#       context: ./server/api
#       dockerfile: Dockerfile
#     restart: always
#     depends_on:
#       - zookeeper
#       - kafka
#     environment:
#       PORT: 3000
#       kafkaHost: kafka:9092
#     #volumes:
#     # - ./node/index.js:/app/index.js
#     ports:
#       - 8000:8000
# ###############-VERSION-###################
# version: '3.7'

# ################-SERVICIOS-################
# services:
# #################-node-Api-############################
  node-api:
    container_name: api-login
    restart: always
    build:
      context: ./server/api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

#################-node-Api-blocked-############################
  node-api-blocked:
     container_name: api-blocked
     restart: always
     build:
       context: ./server/error/
       dockerfile: Dockerfile
     ports:
       - "8000:8000"
     volumes:
      - ./server/api:/app/main.js
# ###################-CLIENTE-###########################
#    cliente:
#     container_name: cliente
#     build: ./client
#     ports:
#         - "4000:4000"
#     depends_on:
#         - node-api
#         - node-api-blocked

# #################-zookeeper-############################

#    zookeeper:
#     image: confluentinc/cp-zookeeper:5.3.1
#     ports:
#       - '2181:2181'
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider

#   #  zookeeper:
#   #   image: 'bitnami/zookeeper:latest'
#   #   ports:
#   #     - '2181:2181'
#   #   environment:
#   #     - ALLOW_ANONYMOUS_LOGIN=yes

# #################-kafka-############################

#    kafka:
#     image: confluentinc/cp-server:5.4.0
#     depends_on:
#       - zookeeper
#     ports:
#       - '9092:9092'
#       - '29092:29092'
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#       KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
#       CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
#       CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
#       CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
#       CONFLUENT_METRICS_ENABLE: 'true'
#       CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

#   #  kafka:
#   #   container_name: elkafka
#   #   image: 'bitnami/kafka:2.8.1'
#   #   ports:
#   #     - '9092:9092'
#   #   environment:
#   #     KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
#   #     KAFKA_BROKER_ID: "1"
#   #     KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
#   #     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
#   #     ALLOW_PLAINTEXT_LISTENER: "yes"
#   #   depends_on:
#   #     - zookeeper
